server:
  port: 8086
  error:
    include-message: always
    include-binding-errors: always
    include-exception: false

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Aguila123456789
    url: jdbc:mysql://localhost:3306/libreapp
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

